// File: app/layout.tsx
import localFont from "next/font/local";
import TopHeader from "@/components/header/TopHeader";
import MainHeader from "@/components/header/MainHeader";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/Footer/Footer";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <TopHeader />
          <MainHeader />
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
  
  );
}
